version: '3.8'

services:
    stylegan:
        build: "./docker"
        container_name: "citrine-build"
        volumes:
            - "./artifacts:/build/artifacts"
            - "./docker:/build/docker"
            - "./citrine-client:/build/citrine-client"
            - "./citrine-daemon:/build/citrine-daemon"
            - "./citrine-ui:/build/citrine-ui"
        working_dir: "/build"
        entrypoint: ["/build/docker/build-all.sh"]
        dns:
            - '8.8.8.8'


