version: '3.8'

services:
    stylegan:
        build: "./docker"
        container_name: "hivemind-build"
        volumes:
            - "./artifacts:/build/artifacts"
            - "./docker:/build/docker"
            - "./hivemind-client:/build/hivemind-client"
            - "./hivemind-daemon:/build/hivemind-daemon"
            - "./hivemind-ui:/build/hivemind-ui"
        working_dir: "/build"
        entrypoint: ["/build/docker/build-all.sh"]


