#! /bin/bash

SRC_DIR="$(dirname "${BASH_SOURCE[0]}")"
cd "$SRC_DIR"
cd ..

set -ex

cd artifacts

rm -rf citrine-linux || true
mkdir citrine-linux
rsync -r citrine-daemon-linux/ citrine-linux/
rsync -r citrine-client-linux/ citrine-linux/
rsync -r citrine-ui-linux/ citrine-linux/
